### ISSUE TITLE
Encountering issues with import datasets in preprocess_feedback_spreadsheet.py

### ISSUE THREAD

**Issue by JamesTu-jtjt** [nyu-mll/ILF-for-code-generation#1]
After building the virtual environment and executing the command: bash ilf_pipeline.sh -d $(pwd) -n test
I get the Error message: 

Traceback (most recent call last):
  File "preprocess_feedback_spreadsheet.py", line 4, in <module>
    from datasets import Dataset, load_dataset
  File "/mnt/c/ifl/Lib/site-packages/datasets/__init__.py", line 24, in <module>
    import pyarrow
  File "/mnt/c/ifl/Lib/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ModuleNotFoundError: No module named 'pyarrow.lib'

I have tried uninstalling and reinstalling datasets and pyarrow, but I still get the same error and can't seem to find much resources online that can help. 
My virtual environment is built with python venv on windows 10. 
Any help or suggestions would be appreciated!

**Comment by damengdameng** [comment]
Hi, May I ask if you have successfully run the whole process?
